"""initial_schema

Revision ID: dddb41b73195
Revises: 
Create Date: 2026-04-23 02:10:03.566930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddb41b73195'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('old_rate', sa.Float(), nullable=True),
    sa.Column('new_rate', sa.Float(), nullable=True),
    sa.Column('delta_cents', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('acknowledged', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_alerts_created_at'), ['created_at'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('supplier_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_started_at'), ['started_at'], unique=False)

    op.create_table('standard_service_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utility', sa.String(length=64), nullable=False),
    sa.Column('rate_cents_kwh', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utility', 'effective_from', name='uq_utility_effective_from')
    )
    with op.batch_alter_table('standard_service_rates', schema=None) as batch_op:
        batch_op.create_index('ix_standard_service_utility', ['utility'], unique=False)

    op.create_table('supplier_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('rate_cents_kwh', sa.Float(), nullable=False),
    sa.Column('contract_term_months', sa.Integer(), nullable=True),
    sa.Column('renewable_pct', sa.Float(), nullable=True),
    sa.Column('cancellation_fee', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_name', 'scraped_at', name='uq_supplier_scraped')
    )
    with op.batch_alter_table('supplier_rates', schema=None) as batch_op:
        batch_op.create_index('ix_supplier_rates_name_scraped', ['supplier_name', 'scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_rates_scraped_at'), ['scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_rates_supplier_name'), ['supplier_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_rates_supplier_name'))
        batch_op.drop_index(batch_op.f('ix_supplier_rates_scraped_at'))
        batch_op.drop_index('ix_supplier_rates_name_scraped')

    op.drop_table('supplier_rates')
    with op.batch_alter_table('standard_service_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_standard_service_utility')

    op.drop_table('standard_service_rates')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_started_at'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_alert_type'))

    op.drop_table('price_alerts')
    # ### end Alembic commands ###
